### ISSUE TITLE
Pull Request da Tradução no Learnyounode !

### ISSUE THREAD

**Issue by lucasfcosta** [lucasfcosta/learnyounode-pt-br#31]
Olá, amigos, bom, vim apenas avisá-los que fui verificar como andava o projeto no [Repositório Original do Learnyounode](https://github.com/rvagg/learnyounode) e acabei descobrindo que agora eles estão aceitando arquivos de tradução, ou seja, **não é mais necessário fazer uma republicação completa do package**.

Sendo assim **fiz um fork do repositório, organizei dentro dele os nossos arquivos de tradução e enviei um [pull-request](https://github.com/rvagg/learnyounode/pull/189) com o link do nosso repositório na descrição**. Gostaria de agradecer imensamente à todos os colaboradores e avisar também que não precisamos parar por aqui, as revisões podem continuar à serem feitas. Podemos manter esse repositório como um registro do trabalho e também como um meio de organizarmos a continuação das revisões. Peço àqueles que fizerem traduções que façam pull-requests nesse repositório e também, caso queiram, no repositório oficial do Learnyounde.

Obrigado à todos!

**Comment by lucasfcosta** [comment]
Estamos lá!
@ericdouglas 
@leonascimento 

Empurrei pra lá os capítulos que vocês traduziram também, [o autor do projeto gostaria que vocês adicionassem seus nomes lá conforme ele pediu nessa issue](https://github.com/rvagg/learnyounode/issues/191), como apenas os capítulos foram empurrados (o resto dos arquivos tiveram que ser re-traduzidos), foram adicionados como colaboradores apenas aqueles que contribuiram com tradução de capítulos.

Ainda assim, o trabalho de todos foi muito importante, irei manter o trabalho original aqui para caso alguém queira consultar.

Quanto às revisões: elas ainda podem ser feitas, o resultado será empurrado para o branch master do projeto original.

**Comment by ericdouglas** [comment]
Ótimo @lucasfcosta !!! Vou ver certinho tudo que rolou em breve!

Vamos continuar lá agora! :smile:

**Comment by leonascimento** [comment]
vlw @lucasfcosta

**Comment by lucasfcosta** [comment]
Recado dado, fechando issue!
